refactor substance page for compound saving in substance form
Chemical-Curation/chemcurator_vuejs pull request #149
Opened 2021-01-04 20:10 UTC by debboutr

2021-01-05 15:05 UTC, michael-barbour commented on src/components/ChemicalEditors.vue
> +        console.log("watcher", this.definedCompound.attributes.molfileV3000);
log

2021-01-05 15:09 UTC, michael-barbour commented on src/components/KetcherWindow.vue
> +      console.log("clearing...");
log

2021-01-05 15:10 UTC, michael-barbour commented on src/components/KetcherWindow.vue
> +        console.log("loading...", molfile);
log

2021-01-05 15:28 UTC, michael-barbour commented on src/components/KetcherWindow.vue
> +        console.log("loading...", molfile);
Added on a draft PR.  Resolving.

2021-01-06 19:25 UTC, hausman-gdit commented
It looks like clearing the marvin window was removed.

"Sample Substance 2" -> search "Solo Substance" , there is still an illdefined compound

![149-ill-defined](https://user-images.githubusercontent.com/74921039/103811516-01dcde80-502b-11eb-85d9-9dbf5fb1f4fe.png)

2021-01-12 17:14 UTC, michael-barbour commented
Looking at this solution, I'm not sure it achieves the ask for "A plan for refactoring and use of the store is outlined and documented".  I was of the impression this ticket was supposed to facilitate team discussion and hopefully have us reach a more unified goal.

There was the offer to start a discussion last Thursday (01-07) that never actually got started, but I think that's a good idea and necessary for this ticket.

Some of my specific concerns are related to how code will have to be written using VueX as a data store and how non-reusable components become when we tie them to a specific piece of data within a VueX store.

2021-01-15 17:58 UTC, michael-barbour requested changes
Console logs that were left in.  We use `npm build` and it has a rule that we cannot build with `console.logs`

**edit: Removed in `52f390c `

2021-01-15 17:58 UTC, michael-barbour commented on src/components/substance/SubstanceForm.vue
> +        console.log("patch", payload);
Log
```suggestion
```

2021-01-15 17:58 UTC, michael-barbour commented on src/components/substance/SubstanceForm.vue
> +        console.log("post", payload);
Log
```suggestion
```

2021-01-15 17:58 UTC, michael-barbour commented on src/components/substance/SubstanceForm.vue
> +      console.log("response", response);
Log
```suggestion
```

2021-01-15 17:58 UTC, michael-barbour commented on src/components/substance/SubstanceForm.vue
> +      console.log("errors", err.response);
Log
```suggestion
```

2021-01-15 17:58 UTC, michael-barbour commented on src/components/substance/SubstanceForm.vue
> +          console.log(error.detail);
Log
```suggestion
```

2021-01-15 17:58 UTC, michael-barbour commented on src/components/substance/SubstanceForm.vue
> +      console.log("nonfield", nonField);
Log
```suggestion
```

2021-01-26 21:13 UTC, michael-barbour approved these changes
Tests are passing with the seed data.

This resolves 3 tickets but it looks like all of their requirements are met here too.

2021-01-26 21:13 UTC, merged